
package homework5service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.11
 * Thu Mar 20 12:00:25 CET 2025
 * Generated source version: 3.5.11
 */

@XmlRootElement(name = "checkETicketValidityResponse", namespace = "http://homework5service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checkETicketValidityResponse", namespace = "http://homework5service/")

public class CheckETicketValidityResponse {

    @XmlElement(name = "return")
    private boolean _return;

    public boolean getReturn() {
        return this._return;
    }

    public void setReturn(boolean new_return)  {
        this._return = new_return;
    }

}

