package homework5service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-20T12:27:54.961+01:00
 * Generated source version: 3.5.11
 *
 */
@WebServiceClient(name = "ETicketServiceImpl",
                  wsdlLocation = "http://localhost:8080/homework5/wsdl/eticketserviceimpl.wsdl",
                  targetNamespace = "http://homework5service/")
public class ETicketServiceImpl extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://homework5service/", "ETicketServiceImpl");
    public static final QName ETicketServiceImplPort = new QName("http://homework5service/", "ETicketServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/homework5/wsdl/eticketserviceimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ETicketServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/homework5/wsdl/eticketserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ETicketServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ETicketServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ETicketServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ETicketServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ETicketServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ETicketServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ETicketServiceImplPortType
     */
    @WebEndpoint(name = "ETicketServiceImplPort")
    public ETicketServiceImplPortType getETicketServiceImplPort() {
        return super.getPort(ETicketServiceImplPort, ETicketServiceImplPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ETicketServiceImplPortType
     */
    @WebEndpoint(name = "ETicketServiceImplPort")
    public ETicketServiceImplPortType getETicketServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ETicketServiceImplPort, ETicketServiceImplPortType.class, features);
    }

}
