
package homework5service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-20T12:27:54.871+01:00
 * Generated source version: 3.5.11
 *
 */
public final class ETicketServiceImplPortType_ETicketServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://homework5service/", "ETicketServiceImpl");

    private ETicketServiceImplPortType_ETicketServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ETicketServiceImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ETicketServiceImpl ss = new ETicketServiceImpl(wsdlURL, SERVICE_NAME);
        ETicketServiceImplPortType port = ss.getETicketServiceImplPort();

        {
        System.out.println("Invoking checkETicketValidity...");
        int _checkETicketValidity_eTicketId = 13;
        boolean _checkETicketValidity__return = port.checkETicketValidity(_checkETicketValidity_eTicketId);
        System.out.println("checkETicketValidity.result=" + _checkETicketValidity__return);


        }
        {
        System.out.println("Invoking generateETicket...");
        int _generateETicket_athleteId = 1;
        homework5service.ETicket _generateETicket__return = port.generateETicket(_generateETicket_athleteId);
        System.out.println("generateETicket.result=" + _generateETicket__return);


        }

        System.exit(0);
    }

}
