package homework5service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-20T12:27:54.954+01:00
 * Generated source version: 3.5.11
 *
 */
@WebService(targetNamespace = "http://homework5service/", name = "ETicketServiceImplPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ETicketServiceImplPortType {

    @WebMethod
    @RequestWrapper(localName = "checkETicketValidity", targetNamespace = "http://homework5service/", className = "homework5service.CheckETicketValidity")
    @ResponseWrapper(localName = "checkETicketValidityResponse", targetNamespace = "http://homework5service/", className = "homework5service.CheckETicketValidityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean checkETicketValidity(

        @WebParam(name = "eTicketId", targetNamespace = "http://homework5service/")
        int eTicketId
    );

    @WebMethod
    @RequestWrapper(localName = "generateETicket", targetNamespace = "http://homework5service/", className = "homework5service.GenerateETicket")
    @ResponseWrapper(localName = "generateETicketResponse", targetNamespace = "http://homework5service/", className = "homework5service.GenerateETicketResponse")
    @WebResult(name = "return", targetNamespace = "")
    public homework5service.ETicket generateETicket(

        @WebParam(name = "athleteId", targetNamespace = "http://homework5service/")
        int athleteId
    );
}
