
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package homework5service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-20T12:27:54.940+01:00
 * Generated source version: 3.5.11
 *
 */

@javax.jws.WebService(
                      serviceName = "ETicketServiceImpl",
                      portName = "ETicketServiceImplPort",
                      targetNamespace = "http://homework5service/",
                      wsdlLocation = "http://localhost:8080/homework5/wsdl/eticketserviceimpl.wsdl",
                      endpointInterface = "homework5service.ETicketServiceImplPortType")

public class ETicketServiceImplPortImpl implements ETicketServiceImplPortType {

    private static final Logger LOG = Logger.getLogger(ETicketServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see homework5service.ETicketServiceImplPortType#checkETicketValidity(int eTicketId)*
     */
    public boolean checkETicketValidity(int eTicketId) {
        LOG.info("Executing operation checkETicketValidity");
        System.out.println(eTicketId);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see homework5service.ETicketServiceImplPortType#generateETicket(int athleteId)*
     */
    public homework5service.ETicket generateETicket(int athleteId) {
        LOG.info("Executing operation generateETicket");
        System.out.println(athleteId);
        try {
            homework5service.ETicket _return = new homework5service.ETicket();
            _return.setId(280607110);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2025-03-20T12:27:54.952+01:00"));
            _return.setAthleteId(-1135417281);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
